---
- name: Télécharger WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraire WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copier WordPress dans /var/www/html
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    remote_src: yes

- name: Supprimer la page par défaut Apache
  file:
    path: /var/www/html/index.html
    state: absent

- name: Configurer wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php

- name: Permissions sur WordPress
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes
